FROM golang:1.19-alpine as build

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY . .

RUN go mod download

RUN air init

CMD ["air"]

# docker build -f Dockerfile_dev -t imguessr-dev . && docker run -p 8080:8080 -v "${PWD}:/app" imguessr-dev