version: "3"
services:
  api:
    build:
      context: .
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017
    env_file:
      - .env
    ports:
      - "8080:8080"
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: