version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_dev
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}:/app"
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
