services:
  api:
    build:
        dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: rebuild
          path: .
    volumes:
      - cache:/root/.cache/go-build

  mongo-gui:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017

volumes:
  cache: