services:
  api:
    build:
        dockerfile: Dockerfile_dev
    volumes:
      - "${PWD}:/app"
    command: >
      sh -c "
      go install github.com/go-delve/delve/cmd/dlv@latest &&
      dlv debug /app/cmd/api --headless --listen=:2345 --api-version=2 --log"
    ports:
      - 2345:2345