services:
  api:
    build:
        dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: rebuild
          path: .
    volumes:
      - cache:/root/.cache/go-build

volumes:
  cache: